import { useEffect, useRef, useCallback } from 'react';
import './ElectricBorder.css';

const ElectricBorder = ({ children, color = '#5227FF', speed = 1, chaos = 0.12, borderRadius = 24, className, style }) => {
  const canvasRef = useRef(null), containerRef = useRef(null), animationRef = useRef(null), timeRef = useRef(0), lastFrameTimeRef = useRef(0);
  const random = useCallback(x => (Math.sin(x * 12.9898) * 43758.5453) % 1, []);
  const noise2D = useCallback((x,y) => { const i=Math.floor(x),j=Math.floor(y),fx=x-i,fy=y-j; const a=random(i+j*57),b=random(i+1+j*57),c=random(i+(j+1)*57),d=random(i+1+(j+1)*57); const ux=fx*fx*(3-2*fx),uy=fy*fy*(3-2*fy); return a*(1-ux)*(1-uy)+b*ux*(1-uy)+c*(1-ux)*uy+d*ux*uy; },[random]);
  const octavedNoise = useCallback((x,octaves,lacunarity,gain,baseAmplitude,baseFrequency,time,seed,baseFlatness) => { let y=0,amplitude=baseAmplitude,frequency=baseFrequency; for(let i=0;i<octaves;i++){let octaveAmplitude=amplitude;if(i===0) octaveAmplitude*=baseFlatness;y+=octaveAmplitude*noise2D(frequency*x+seed*100,time*frequency*.3);frequency*=lacunarity;amplitude*=gain;} return y; },[noise2D]);
  const getCornerPoint = useCallback((cx,cy,r,startAngle,arcLength,progress)=>{const angle=startAngle+progress*arcLength;return{x:cx+r*Math.cos(angle),y:cy+r*Math.sin(angle)};},[]);
  const getRoundedRectPoint = useCallback((t,left,top,width,height,radius)=>{const sw=width-2*radius,sh=height-2*radius,ca=Math.PI*radius/2,tp=2*sw+2*sh+4*ca,d=t*tp;let a=0;if(d<=a+sw){const p=(d-a)/sw;return{x:left+radius+p*sw,y:top};}a+=sw;if(d<=a+ca){const p=(d-a)/ca;return getCornerPoint(left+width-radius,top+radius,radius,-Math.PI/2,Math.PI/2,p);}a+=ca;if(d<=a+sh){const p=(d-a)/sh;return{x:left+width,y:top+radius+p*sh};}a+=sh;if(d<=a+ca){const p=(d-a)/ca;return getCornerPoint(left+width-radius,top+height-radius,radius,0,Math.PI/2,p);}a+=ca;if(d<=a+sw){const p=(d-a)/sw;return{x:left+width-radius-p*sw,y:top+height};}a+=sw;if(d<=a+ca){const p=(d-a)/ca;return getCornerPoint(left+radius,top+height-radius,radius,Math.PI/2,Math.PI/2,p);}a+=ca;if(d<=a+sh){const p=(d-a)/sh;return{x:left,y:top+height-radius-p*sh};}a+=sh;const p=(d-a)/ca;return getCornerPoint(left+radius,top+radius,radius,Math.PI,Math.PI/2,p);},[getCornerPoint]);
  useEffect(()=>{const canvas=canvasRef.current,container=containerRef.current;if(!canvas||!container)return;const ctx=canvas.getContext('2d');if(!ctx)return;const octaves=10,lacunarity=1.6,gain=.7,amplitude=chaos,frequency=10,baseFlatness=0,displacement=60,borderOffset=60;const updateSize=()=>{const rect=container.getBoundingClientRect(),width=rect.width+borderOffset*2,height=rect.height+borderOffset*2,dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=width*dpr;canvas.height=height*dpr;canvas.style.width=`${width}px`;canvas.style.height=`${height}px`;return{width,height};};let {width,height}=updateSize(),lastDpr=Math.min(window.devicePixelRatio||1,2);
    const draw=currentTime=>{const dpr=Math.min(window.devicePixelRatio||1,2);if(dpr!==lastDpr){lastDpr=dpr;({width,height}=updateSize());}const delta=(currentTime-lastFrameTimeRef.current)/1000;timeRef.current+=delta*speed;lastFrameTimeRef.current=currentTime;ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,canvas.width,canvas.height);ctx.scale(dpr,dpr);ctx.strokeStyle=color;ctx.lineWidth=1;ctx.lineCap='round';ctx.lineJoin='round';const left=borderOffset,top=borderOffset,bw=width-2*borderOffset,bh=height-2*borderOffset,maxRadius=Math.min(bw,bh)/2,radius=Math.min(borderRadius,maxRadius),perimeter=2*(bw+bh)+2*Math.PI*radius,samples=Math.floor(perimeter/2);ctx.beginPath();for(let i=0;i<=samples;i++){const progress=i/samples,point=getRoundedRectPoint(progress,left,top,bw,bh,radius),xn=octavedNoise(progress*8,octaves,lacunarity,gain,amplitude,frequency,timeRef.current,0,baseFlatness),yn=octavedNoise(progress*8,octaves,lacunarity,gain,amplitude,frequency,timeRef.current,1,baseFlatness),x=point.x+xn*displacement,y=point.y+yn*displacement;i===0?ctx.moveTo(x,y):ctx.lineTo(x,y);}ctx.closePath();ctx.stroke();animationRef.current=requestAnimationFrame(draw);};const ro=new ResizeObserver(()=>({width,height}=updateSize()));ro.observe(container);animationRef.current=requestAnimationFrame(draw);return()=>{if(animationRef.current)cancelAnimationFrame(animationRef.current);ro.disconnect();};},[color,speed,chaos,borderRadius,octavedNoise,getRoundedRectPoint]);
  const vars={'--electric-border-color':color,borderRadius};
  return <div ref={containerRef} className={`electric-border ${className??''}`} style={{...vars,...style}}><div className="eb-canvas-container"><canvas ref={canvasRef} className="eb-canvas"/></div><div className="eb-layers"><div className="eb-glow-1"/><div className="eb-glow-2"/><div className="eb-background-glow"/></div><div className="eb-content">{children}</div></div>;
};
export default ElectricBorder;
